name: Picons Builder

on:
  schedule:
    - cron:  '20 17 * * 3'
  workflow_dispatch:

jobs:
  picons_builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build --no-cache -t ghcr.io/sharkydapirate/picons-builder:latest .
      - name: Tag image
        if: ${{ github.ref == format('refs/heads/master') }}
        run: |
          docker tag ghcr.io/sharkydapirate/picons-builder:latest ghcr.io/sharkydapirate/picons-builder:$(date +%F)
